### ISSUE TITLE
Feature request - google search concatination like Alamut

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/moka-fe#141]
Is there a way to add a similar google search concatenation like they have in Alamut that searches for "all" possible ways of writing a variant? 
![google search](https://cloud.githubusercontent.com/assets/24274883/21394880/4c5fbf7a-c792-11e6-8741-ed11f6c92670.JPG)

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
