### ISSUE TITLE
Change PGD tab in booking in page

### ISSUE THREAD

**Issue by woook** [moka-guys/moka-fe#146]
From: Coldwell Michael [mailto:Michael.Coldwell@viapath.co.uk] 
Sent: 10 January 2017 15:01
To: AHN, JooWook (GUY'S AND ST THOMAS' NHS FOUNDATION TRUST) <joowook.ahn@nhs.net>
Subject: windows 7 and PDS moka booking in

Hi Wook
You wanted me to email you about changing the 'PGD'  tab in the [booking in array request] page to make it a clone of the 'PGD Cycles' tab in [Patient details]
Thank you very much
Mike

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
