### ISSUE TITLE
PGD array report template

### ISSUE THREAD

**Issue by sbint** [moka-guys/moka-fe#199]
For PGD cases please can we get a new tab put in the mother's patient page under the "PGD cycles" tab called "Satellite centre"  and then would it be possible to have a drop down to select if it's:
Exeter satellite centre
Leeds satellite centre
Sheffield satellite centre

If one of these is selected then can this text go in the recipient address slot on the report rather than Yacoub's address. If it needs Yacoub's address is it ok for us not to select anything and this will be the default address that comes up on the report? 
If this is not possible and we have to select one address (including Yacoub's) then can we have the tab called "Recipient address" and have the dropdowns as:
Yacoub Khalaf - and what comes up on the report is the current address
Exeter satellite centre
Leeds satellite centre
Sheffield satellite centre

Thanks!

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
