### ISSUE TITLE
572 UnreportedRushArrays

### ISSUE THREAD

**Issue by mikecoldwell** [moka-guys/moka-fe#213]
Hello, This audit (572) is half way through a transition to become more like 570 UnreportedArrayPatients. It still needs to stop displaying patients received over a year ago and to show and to have a little '+' symbol that expands to show the patient notes. Check out (570) to see what I'm talking about. This change has been agreed with Wook.

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
