### ISSUE TITLE
Minor Moka WES update : To include DNA conc. for family DNAs

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/moka-fe#228]
The family DNAs button on the WES results page in Moka produces a table from GeneWorks with details of family members with DNA available.  Could this table also display the DNA concentration?

This would an incredible about of time and faffage as we could create Sanger sequencing worksheets for family members without going through GeneWorks.

**Comment by andyb3** [comment]
This is an array form, @woook would adding the concentration (Qubit I presume?) to the family DNA page be OK?

**Comment by SueLillis** [comment]
Hi Andy,

Yes I would be perfect to add this to the DNA family page. And the nanodrop concentration from geneworks is all we need as this is sufficient for sanger confirmations.
E.g. - could have a column right beside DNA number in screen shot below.

[cid:image001.png@01D31CF5.491DC790]


Thanks
Sue

**Comment by woook** [comment]
I think there are a few DNA conc related issues - would be good to do all this together.
#198 
also another issue I can't find about showing Qubit conc field on some forms - I think @mcoldwell knows which forms they are.

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
