### ISSUE TITLE
prevent 'phenotype only' genes from being selected into gene panels

### ISSUE THREAD

**Issue by aledj2** [moka-guys/moka-fe#233]

**Comment by woook** [comment]
what is a phenotype only gene?

**Comment by aledj2** [comment]
eg http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:350

**Comment by aledj2** [comment]
has a gene symbol, hgncid etc but no coordinates, just a locus associated with a syndrome

**Comment by woook** [comment]
Can you differentiate between these and proper genes in HGNC?

**Comment by aledj2** [comment]
yep, locus type is a field. Am having to work around these when testing the number of genes in the coverage report == number of genes in coverage report as they will be in HGNC table but not in Pan493 therefore failing the test

**Comment by woook** [comment]
who/how are these phenotype associated "genes" being added to panels in the first place?

**Comment by aledj2** [comment]
They are in Moka, and were included in an early microcephaly panel that I think was curated by Ana but used for a number of analyses



Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________

**Comment by woook** [comment]
Have changed this to feature request as we are making Moka the guardian of preventing people from selecting non-valid gene symbols.

**Comment by aledj2** [comment]
the coverage report script checks for any genes that are in Pan493 that aren't in the coverage report (ie genes where coverage would be expected - therefore having phenotype only genes won't break this. 

May be worth limiting the genes in the gene selection page to those in Pan493 rather than using locustype as there are some locustypes which some genes are in pan493, whilst others aren't so are not a good filter.

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
