### ISSUE TITLE
WES DNA QC request

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/moka-fe#311]
Hi guys,

Got a couple of change requests for the DNA QC from Lina:
-	For DNA QC, be able to select a certain number of samples from the list, sort these into DNA number order and print out only these samples on a worksheet. (At the moment the entire list is printed without any chance of modifying it /Matt)
-	When a batch is made for NGS make it possible to export a csv from Moka instead of doing this in Geneworks. The csv should be in the same format as the one created in Geneworks but include the Qubit concentration instead of the nanodrop concentration that we currently get from Geneworks. (Could be exported from the Batch view, then we can sort beforehand /Matt)

It would save us a lot of time in terms of lab work and will mean we don’t have to duplicate data entry which we are currently doing and is a bit of a waste of time.

Thanks 
Lina

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
