### ISSUE TITLE
Form 7030 PGD (array PGD results) shows wrong cy dye

### ISSUE THREAD

**Issue by woook** [moka-guys/moka-fe#36]
This form shows all embryos as being labelled in Cy5. However due to a change in process, this is no longer true. Change form to show actual Cy dye used.

**Comment by andyb3** [comment]
Is this still an issue?

**Comment by woook** [comment]
Yes.

Array PGD results form (form 7030) hyb ID fields shows all of them as Cy5 by default when this is not always the case.

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
