### ISSUE TITLE
Prenatals QF-PCR, incomplete on MOKA 

### ISSUE THREAD

**Issue by helenthomas** [moka-guys/moka-fe#466]
Activate the second PCR check button in MOKA so PCR sex will be checked before going on array runsheet.

**Comment by aledj2** [comment]
Hi Helen, 
For future issues can you use this url please https://github.com/moka-guys/helpdesk/issues

**Comment by woook** [comment]
Hi Helen, please could you tell on which page/form you need this to be shown?
Thanks

**Comment by helenthomas** [comment]
[cid:image002.jpg@01D3B550.31231430]

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
