### ISSUE TITLE
Update 807020 Exome Lab

### ISSUE THREAD

**Issue by Graeme-Smith** [moka-guys/moka-fe#659]
Update 807020 Exome Lab to only show probands in trios at certain statuses. Ensure that statuses of non-probands are still updated along with probands when they are not visible. Improve loading speed of WES Dashboard.
erin_dev/WES_Dashboard_Tissue_Audit_master_26Oct2020

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
