### ISSUE TITLE
the comments don't match the code

### ISSUE THREAD

**Issue by aledj2** [moka-guys/moka-fe#662]
A change seems to have been made then accidentally deleted - please change back to feb59ea5f606e8e076fe84ce30e237d19991ea00
https://github.com/moka-guys/moka-fe/blob/810682c01c6eb220c2f66f7e19e43a1e26ee9a96/forms/4752%20DeletePatientRecords#L17

**Comment by RachelDuffin** [comment]
Obsolete as Moka is being wound down
